package com.github.waitlight.asskicker.integration;

import com.github.waitlight.asskicker.repository.RegistrationLock;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.reactive.server.WebTestClient;
import reactor.core.publisher.Mono;

import java.util.LinkedHashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
@AutoConfigureWebTestClient
class ChannelApiIntegrationTest {

    @Autowired
    private WebTestClient webTestClient;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setUp() {
        databaseClient.sql("DROP TABLE IF EXISTS t_user")
                .fetch()
                .rowsUpdated()
                .then()
                .block();
        databaseClient.sql("DROP TABLE IF EXISTS t_channel")
                .fetch()
                .rowsUpdated()
                .then()
                .block();
        databaseClient.sql("""
                CREATE TABLE t_user (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(100) NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    role VARCHAR(20) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    created_at BIGINT NOT NULL,
                    updated_at BIGINT,
                    last_login_at BIGINT,
                    CONSTRAINT uk_t_user_username UNIQUE (username)
                )
                """)
                .fetch()
                .rowsUpdated()
                .then()
                .block();
        databaseClient.sql("""
                CREATE TABLE t_channel (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    type VARCHAR(100) NOT NULL,
                    description VARCHAR(1000),
                    properties TEXT NOT NULL,
                    created_at BIGINT NOT NULL,
                    updated_at BIGINT
                )
                """)
                .fetch()
                .rowsUpdated()
                .then()
                .block();
    }

    @Test
    void channelCrudFlow() {
        String token = registerAndLogin();

        Map<String, Object> properties = new LinkedHashMap<>();
        properties.put("apiKey", "plain-secret");
        properties.put("host", "smtp.example.com");

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("name", "Email Channel");
        body.put("type", "EMAIL");
        body.put("description", "desc");
        body.put("properties", properties);

        Map<String, Object> created = webTestClient.post()
                .uri("/api/channels")
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(body)
                .exchange()
                .expectStatus().isCreated()
                .expectBody(Map.class)
                .returnResult()
                .getResponseBody();

        assertNotNull(created);
        Number channelIdNumber = (Number) created.get("id");
        assertNotNull(channelIdNumber);
        long channelId = channelIdNumber.longValue();
        Map<String, Object> createdProperties = (Map<String, Object>) created.get("properties");
        assertNotNull(createdProperties);
        assertEquals("plain-secret", createdProperties.get("apiKey"));

        webTestClient.get()
                .uri("/api/channels/{id}", channelId)
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$.name").isEqualTo("Email Channel")
                .jsonPath("$.type").isEqualTo("EMAIL")
                .jsonPath("$.properties.apiKey").isEqualTo("plain-secret");

        webTestClient.get()
                .uri("/api/channels")
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$[0].id").isNumber();

        Map<String, Object> updateBody = new LinkedHashMap<>();
        updateBody.put("name", "Email Channel Updated");
        updateBody.put("type", "EMAIL");
        updateBody.put("description", "desc2");
        updateBody.put("properties", Map.of("apiKey", "new-secret"));

        webTestClient.put()
                .uri("/api/channels/{id}", channelId)
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(updateBody)
                .exchange()
                .expectStatus().isOk()
                .expectBody()
                .jsonPath("$.name").isEqualTo("Email Channel Updated")
                .jsonPath("$.type").isEqualTo("EMAIL")
                .jsonPath("$.properties.apiKey").isEqualTo("new-secret");

        webTestClient.delete()
                .uri("/api/channels/{id}", channelId)
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                .exchange()
                .expectStatus().isNoContent();
    }

    @Test
    void rejectsInvalidChannelType() {
        String token = registerAndLogin();

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("name", "Bad Channel");
        body.put("type", "INVALID");
        body.put("description", "desc");
        body.put("properties", Map.of());

        webTestClient.post()
                .uri("/api/channels")
                .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(body)
                .exchange()
                .expectStatus().isBadRequest()
                .expectBody(String.class)
                .value(message -> assertEquals("渠道类型必须为SMS、EMAIL、IM、PUSH", message));
    }

    private String registerAndLogin() {
        webTestClient.post()
                .uri("/api/auth/register")
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(Map.of("username", "admin", "password", "pass"))
                .exchange()
                .expectStatus().isOk();

        Map<String, Object> tokenResponse = webTestClient.post()
                .uri("/api/auth/login")
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(Map.of("username", "admin", "password", "pass"))
                .exchange()
                .expectStatus().isOk()
                .expectBody(Map.class)
                .returnResult()
                .getResponseBody();

        assertNotNull(tokenResponse);
        Object accessToken = tokenResponse.get("accessToken");
        assertNotNull(accessToken);
        return accessToken.toString();
    }

    @TestConfiguration
    static class TestConfig {
        @Bean
        @Primary
        RegistrationLock registrationLock() {
            return () -> Mono.empty();
        }
    }
}
