version: '3.8'

services:
  namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    networks:
      - rocketmq

  broker:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=namesrv:9876
    command: >
      sh -c "grep -q '^brokerIP1=' /home/rocketmq/rocketmq-5.1.4/conf/broker.conf
      || echo 'brokerIP1=host.docker.internal' >> /home/rocketmq/rocketmq-5.1.4/conf/broker.conf;
      grep -q '^autoCreateTopicEnable=' /home/rocketmq/rocketmq-5.1.4/conf/broker.conf
      || echo 'autoCreateTopicEnable=true' >> /home/rocketmq/rocketmq-5.1.4/conf/broker.conf;
      sh mqbroker -n namesrv:9876 -c /home/rocketmq/rocketmq-5.1.4/conf/broker.conf"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - namesrv
    networks:
      - rocketmq

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq

networks:
  rocketmq:
    driver: bridge
