package com.github.waitlight.asskicker.repository;

import com.github.waitlight.asskicker.model.Channel;
import com.github.waitlight.asskicker.model.ChannelType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ActiveProfiles;
import reactor.test.StepVerifier;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
@ActiveProfiles("test")
class ChannelRepositoryTest {

    @Autowired
    private ChannelRepository channelRepository;

    @Autowired
    private DatabaseClient databaseClient;

    @BeforeEach
    void setUp() {
        databaseClient.sql("DROP TABLE IF EXISTS t_channel")
                .fetch()
                .rowsUpdated()
                .then()
                .block();
        databaseClient.sql("""
                CREATE TABLE t_channel (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    type VARCHAR(100) NOT NULL,
                    description VARCHAR(1000),
                    properties TEXT NOT NULL,
                    created_at BIGINT NOT NULL,
                    updated_at BIGINT
                )
                """)
                .fetch()
                .rowsUpdated()
                .then()
                .block();
    }

    @Test
    void shouldPersistAndLoadChannel() {
        Channel channel = new Channel();
        channel.setName("Email Channel");
        channel.setType(ChannelType.EMAIL);
        channel.setDescription("test");
        channel.setPropertiesJson("{\"smtpHost\":\"smtp.example.com\"}");
        channel.setCreatedAt(1L);
        channel.setUpdatedAt(1L);

        StepVerifier.create(channelRepository.save(channel)
                        .flatMap(saved -> channelRepository.findById(saved.getId())))
                .assertNext(found -> {
                    assertNotNull(found.getId());
                    assertEquals("Email Channel", found.getName());
                    assertEquals(ChannelType.EMAIL, found.getType());
                    assertEquals("{\"smtpHost\":\"smtp.example.com\"}", found.getPropertiesJson());
                })
                .verifyComplete();
    }
}
